# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password:
#   socket: /tmp/mysql.sock

default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>



# development:
#   <<: *default
#   database: ekar_development

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: ekar_development


# test:
#   <<: *default
#   database: ekar_test

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: ekar_test


# production:
#   <<: *default
#   database: ekar_production
#   username: ekar
#   password: <%= ENV['EKAR_DATABASE_PASSWORD'] %>

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>



